<?php

/**
 * BaseProjetType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $projet_type_nom
 * @property string $projet_type_code
 * @property string $projet_type_couleur
 * @property Doctrine_Collection $Projets
 * 
 * @method string              getProjetTypeNom()       Returns the current record's "projet_type_nom" value
 * @method string              getProjetTypeCode()      Returns the current record's "projet_type_code" value
 * @method string              getProjetTypeCouleur()   Returns the current record's "projet_type_couleur" value
 * @method Doctrine_Collection getProjets()             Returns the current record's "Projets" collection
 * @method ProjetType          setProjetTypeNom()       Sets the current record's "projet_type_nom" value
 * @method ProjetType          setProjetTypeCode()      Sets the current record's "projet_type_code" value
 * @method ProjetType          setProjetTypeCouleur()   Sets the current record's "projet_type_couleur" value
 * @method ProjetType          setProjets()             Sets the current record's "Projets" collection
 * 
 * @package    adminpicaddy
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProjetType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('projet_type');
        $this->hasColumn('projet_type_nom', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('projet_type_code', 'string', 1, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 1,
             ));
        $this->hasColumn('projet_type_couleur', 'string', 6, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 6,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Projet as Projets', array(
             'local' => 'id',
             'foreign' => 'projet_type_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}