<?php

/**
 * BaseProjetToUtilisateur
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $projet_id
 * @property integer $utilisateur_id
 * @property Projet $Projet
 * @property Utilisateur $Utilisateur
 * 
 * @method integer             getProjetId()       Returns the current record's "projet_id" value
 * @method integer             getUtilisateurId()  Returns the current record's "utilisateur_id" value
 * @method Projet              getProjet()         Returns the current record's "Projet" value
 * @method Utilisateur         getUtilisateur()    Returns the current record's "Utilisateur" value
 * @method ProjetToUtilisateur setProjetId()       Sets the current record's "projet_id" value
 * @method ProjetToUtilisateur setUtilisateurId()  Sets the current record's "utilisateur_id" value
 * @method ProjetToUtilisateur setProjet()         Sets the current record's "Projet" value
 * @method ProjetToUtilisateur setUtilisateur()    Sets the current record's "Utilisateur" value
 * 
 * @package    picadmin
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProjetToUtilisateur extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('projet_to_utilisateur');
        $this->hasColumn('projet_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('utilisateur_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Projet', array(
             'local' => 'projet_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Utilisateur', array(
             'local' => 'utilisateur_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}