<?php

/**
 * BaseUtilisateurToGroupe
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $utilisateur_id
 * @property integer $groupe_id
 * @property Utilisateur $Utilisateur
 * @property Groupe $Groupe
 * 
 * @method integer             getUtilisateurId()  Returns the current record's "utilisateur_id" value
 * @method integer             getGroupeId()       Returns the current record's "groupe_id" value
 * @method Utilisateur         getUtilisateur()    Returns the current record's "Utilisateur" value
 * @method Groupe              getGroupe()         Returns the current record's "Groupe" value
 * @method UtilisateurToGroupe setUtilisateurId()  Sets the current record's "utilisateur_id" value
 * @method UtilisateurToGroupe setGroupeId()       Sets the current record's "groupe_id" value
 * @method UtilisateurToGroupe setUtilisateur()    Sets the current record's "Utilisateur" value
 * @method UtilisateurToGroupe setGroupe()         Sets the current record's "Groupe" value
 * 
 * @package    picadmin
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUtilisateurToGroupe extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('utilisateur_to_groupe');
        $this->hasColumn('utilisateur_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('groupe_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Utilisateur', array(
             'local' => 'utilisateur_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Groupe', array(
             'local' => 'groupe_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}