<?php

/**
 * BaseTacheToUtilisateur
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $tache_id
 * @property integer $utilisateur_id
 * @property Tache $Tache
 * @property Utilisateur $Utilisateur
 * 
 * @method integer            getTacheId()        Returns the current record's "tache_id" value
 * @method integer            getUtilisateurId()  Returns the current record's "utilisateur_id" value
 * @method Tache              getTache()          Returns the current record's "Tache" value
 * @method Utilisateur        getUtilisateur()    Returns the current record's "Utilisateur" value
 * @method TacheToUtilisateur setTacheId()        Sets the current record's "tache_id" value
 * @method TacheToUtilisateur setUtilisateurId()  Sets the current record's "utilisateur_id" value
 * @method TacheToUtilisateur setTache()          Sets the current record's "Tache" value
 * @method TacheToUtilisateur setUtilisateur()    Sets the current record's "Utilisateur" value
 * 
 * @package    picadmin
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTacheToUtilisateur extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tache_to_utilisateur');
        $this->hasColumn('tache_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('utilisateur_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Tache', array(
             'local' => 'tache_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Utilisateur', array(
             'local' => 'utilisateur_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}