<?php

/**
 * BaseIdee
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $idee_nom
 * @property string $idee_description
 * @property integer $idee_utilisateur_id
 * @property integer $idee_projet_id
 * @property integer $idee_statut_id
 * @property Utilisateur $Utilisateur
 * @property Projet $Projet
 * @property Statut $Statut
 * @property Doctrine_Collection $CommentaireToIdee
 * @property Doctrine_Collection $IdeeToDocument
 * 
 * @method string              getIdeeNom()             Returns the current record's "idee_nom" value
 * @method string              getIdeeDescription()     Returns the current record's "idee_description" value
 * @method integer             getIdeeUtilisateurId()   Returns the current record's "idee_utilisateur_id" value
 * @method integer             getIdeeProjetId()        Returns the current record's "idee_projet_id" value
 * @method integer             getIdeeStatutId()        Returns the current record's "idee_statut_id" value
 * @method Utilisateur         getUtilisateur()         Returns the current record's "Utilisateur" value
 * @method Projet              getProjet()              Returns the current record's "Projet" value
 * @method Statut              getStatut()              Returns the current record's "Statut" value
 * @method Doctrine_Collection getCommentaireToIdee()   Returns the current record's "CommentaireToIdee" collection
 * @method Doctrine_Collection getIdeeToDocument()      Returns the current record's "IdeeToDocument" collection
 * @method Idee                setIdeeNom()             Sets the current record's "idee_nom" value
 * @method Idee                setIdeeDescription()     Sets the current record's "idee_description" value
 * @method Idee                setIdeeUtilisateurId()   Sets the current record's "idee_utilisateur_id" value
 * @method Idee                setIdeeProjetId()        Sets the current record's "idee_projet_id" value
 * @method Idee                setIdeeStatutId()        Sets the current record's "idee_statut_id" value
 * @method Idee                setUtilisateur()         Sets the current record's "Utilisateur" value
 * @method Idee                setProjet()              Sets the current record's "Projet" value
 * @method Idee                setStatut()              Sets the current record's "Statut" value
 * @method Idee                setCommentaireToIdee()   Sets the current record's "CommentaireToIdee" collection
 * @method Idee                setIdeeToDocument()      Sets the current record's "IdeeToDocument" collection
 * 
 * @package    adminpicaddy
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseIdee extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('idee');
        $this->hasColumn('idee_nom', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('idee_description', 'string', 1500, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 1500,
             ));
        $this->hasColumn('idee_utilisateur_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('idee_projet_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('idee_statut_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Utilisateur', array(
             'local' => 'idee_utilisateur_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Projet', array(
             'local' => 'idee_projet_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Statut', array(
             'local' => 'idee_statut_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Commentaire as CommentaireToIdee', array(
             'local' => 'id',
             'foreign' => 'commentaire_idee_id'));

        $this->hasMany('Document as IdeeToDocument', array(
             'local' => 'id',
             'foreign' => 'document_idee_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}