<?php

/**
 * BaseGroupe
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $groupe_nom
 * @property Doctrine_Collection $UtilisateurToGroupe
 * 
 * @method string              getGroupeNom()           Returns the current record's "groupe_nom" value
 * @method Doctrine_Collection getUtilisateurToGroupe() Returns the current record's "UtilisateurToGroupe" collection
 * @method Groupe              setGroupeNom()           Sets the current record's "groupe_nom" value
 * @method Groupe              setUtilisateurToGroupe() Sets the current record's "UtilisateurToGroupe" collection
 * 
 * @package    picadmin
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGroupe extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('groupe');
        $this->hasColumn('groupe_nom', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('UtilisateurToGroupe', array(
             'local' => 'id',
             'foreign' => 'groupe_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}