<?php

/**
 * BaseDocument
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $document_nom
 * @property integer $document_note_id
 * @property integer $document_idee_id
 * @property integer $document_bug_id
 * @property Note $Note
 * @property Idee $Idee
 * @property Bug $Bug
 * 
 * @method string   getDocumentNom()      Returns the current record's "document_nom" value
 * @method integer  getDocumentNoteId()   Returns the current record's "document_note_id" value
 * @method integer  getDocumentIdeeId()   Returns the current record's "document_idee_id" value
 * @method integer  getDocumentBugId()    Returns the current record's "document_bug_id" value
 * @method Note     getNote()             Returns the current record's "Note" value
 * @method Idee     getIdee()             Returns the current record's "Idee" value
 * @method Bug      getBug()              Returns the current record's "Bug" value
 * @method Document setDocumentNom()      Sets the current record's "document_nom" value
 * @method Document setDocumentNoteId()   Sets the current record's "document_note_id" value
 * @method Document setDocumentIdeeId()   Sets the current record's "document_idee_id" value
 * @method Document setDocumentBugId()    Sets the current record's "document_bug_id" value
 * @method Document setNote()             Sets the current record's "Note" value
 * @method Document setIdee()             Sets the current record's "Idee" value
 * @method Document setBug()              Sets the current record's "Bug" value
 * 
 * @package    adminpicaddy
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDocument extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('document');
        $this->hasColumn('document_nom', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('document_note_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('document_idee_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('document_bug_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Note', array(
             'local' => 'document_note_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Idee', array(
             'local' => 'document_idee_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Bug', array(
             'local' => 'document_bug_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}