# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# Main
main:
  url:   /
  param: { module: main, action: index }

# Projets
projets:
  url:   /projets/
  param: { module: projets, action: index }

projetotaches:
  url:  /projets/:id/taches/
  param: { module: projets, action: indexTaches }
  requirements: { id: \d+ }

projetobugs:
  url:  /projets/:id/bugs/
  param: { module: projets, action: indexBugs }
  requirements: { id: \d+ }

projetoidees:
  url:  /projets/:id/idees/
  param: { module: projets, action: indexIdees }
  requirements: { id: \d+ }

projetindex:
  url:   /projets/:id
  param: { module: projets, action: indexProjet }
  requirements: { id: \d+ }


# Taches
taches:
  url:   /taches/
  param: { module: taches, action: index }
  
# Bugs
bugs:
  url:  /bugs/
  param: { module: bugs, action: index }

# Idées
idees:
  url:  /idees/
  param: { module: idees, action: index }

# Notes
notes:
  url:  /notes/
  param: { module: notes, action: index }

# Parametrages
parametrages:
  url:  /parametrages/
  param: { module: parametrages, action: index }

profil:
  url:   /parametrages/profil/
  param: { module: parametrages, action: profil }
  
statut:
  url:  /parametrages/statuts/
  param: { module: parametrages, action: indexStatut }

suppressionstatut:
  url:  /parametrages/statuts/suppressionstatut
  param: { module: parametrages, action: suppressionstatut }

editionstatut:
  url:  /parametrages/statuts/editionstatut
  param: { module: parametrages, action: editionstatut }
  
suppressiontype:
  url:  /parametrages/typeprojets/suppressiontype
  param: { module: parametrages, action: suppressiontype }

editiontype:
  url:  /parametrages/typeprojets/editiontype
  param: { module: parametrages, action: editiontype }

typeprojet:
  url:  /parametrages/typeprojets/
  param: { module: parametrages, action: indexProjetType }
  
utilisateur:
  url:  /parametrages/utilisateurs/
  param: { module: parametrages, action: indexUtilisateur }
  
# Connexion
connexion:
  url: /connexion/
  param: { module: connexion, action: login }

# Deconnexion
deconnexion:
  url: /deconnexion/
  param: { module: connexion, action: logout }

# default rules
homepage:
  url:   /
  param: { module: default, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
