<?php

/**
 * BugTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BugTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BugTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Bug');
    }
}