<?php

/**
 * GroupeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GroupeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GroupeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Groupe');
    }
     public static function getGroupeAll()
    {
        $groupe = Doctrine::getTable('Groupe')
			->createQuery('a')
			->execute();
	return $groupe;

    }
}