<?php

/**
 * IdeeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IdeeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IdeeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Idee');
    }

    public static function getListeIdees() {
	 $liste_idees = Doctrine::getTable('Idee')
			->createQuery('a')
			->execute();
	return $liste_idees;
    }
}