<?php

/**
 * ProjetTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProjetTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProjetTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProjetType');
    }

    public static function getProjetTypeAll()
    {
        $projettype = Doctrine::getTable('ProjetType')
			->createQuery('a')
			->execute();
	return $projettype;
      }
}