<?php

/**
 * ProjetToUtilisateurTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProjetToUtilisateurTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProjetToUtilisateurTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProjetToUtilisateur');
    }
}