<?php

/**
 * ProjetType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    adminpicaddy
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ProjetType extends BaseProjetType
{
    public function getProjetTypeAll()
    {
        return Doctrine_Core::getTable('ProjetType')->getProjetTypeAll();
    }

    public function getProjetTypeById($id)
    {
      return Doctrine_Core::getTable('ProjetType')->getProjetType($id);
    }
    /*
    public function ProjetType($libelle,$couleur,$code)
    {
        
    }*/
}
