<?php

/**
 * Statut
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    adminpicaddy
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Statut extends BaseStatut
{
       public function getStatutAll()
       {
           return  Doctrine_Core::getTable('Statut')->getListeStatut();
       }

       public function getStatutById($id)
       {
           return  Doctrine_Core::getTable('Statut')->getStatutById($id);
       }

       

}
