<?php

/**
 * TacheTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TacheTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TacheTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Tache');
    }
}