<?php

/**
 * UtilisateurTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UtilisateurTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UtilisateurTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Utilisateur');
    }

    public static function getUserByEmailTable($email) {
        $user = Doctrine::getTable('Utilisateur')
			->createQuery('u')
                        ->where('u.utilisateur_email = ?', $email)
			->execute();

	return $user;
    }
}