<?php

/**
 * UtilisateurToGroupeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UtilisateurToGroupeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UtilisateurToGroupeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UtilisateurToGroupe');
    }
}