<?php

/**
 * UtilisateurTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UtilisateurTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UtilisateurTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Utilisateur');
    }

    //Récupérer un utilisateur 
    public static function getUserById($id)
    {
        $q = Doctrine_Query::create()
            ->from('Utilisateur u')
            ->where('u.id = ?', $id);

        $user = $q->fetchOne();

        return $user;
    }

    public static function getUserAll()
    {
        $user = Doctrine::getTable('Utilisateur')
			->createQuery('a')
			->execute();
	return $user;

    }
    
    public static function getUserByEmailTable($email) {
        $user = Doctrine::getTable('Utilisateur')
			->createQuery('u')
                        ->where('u.utilisateur_email = ?', $email)
			->execute();

	return $user;
    }
}