<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/01/22 01:05:04

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=adminpicaddy',
  'username' => 'root',
  'password' => 'utopie',
  'name' => 'doctrine',
)),);
