<?php
// auto-generated by sfSecurityConfigHandler
// date: 2011/02/05 16:17:28
$this->security = array (
  'connexion' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 'admin',
  ),
);
